version: 0.2

env:
  shell: bash
  variables:
    IMAGE_BASE_NAME: "service-icons"
    REGISTRY: "974517877189.dkr.ecr.eu-central-1.amazonaws.com"
    SHELL: /bin/bash
    AWS_DEFAULT_REGION: eu-central-1
    USER: "aws_code_build"
    PIPENV_NOSPIN: 1

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - aws --version
      - echo "Login to AWS ECR docker registry"
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${REGISTRY}
  pre_build:
    commands:
      - echo "Export of the image tag for build and push purposes"
      - echo "CODEBUILD_WEBHOOK_HEAD_REF=${CODEBUILD_WEBHOOK_HEAD_REF} CODEBUILD_WEBHOOK_BASE_REF=${CODEBUILD_WEBHOOK_BASE_REF}"
      - export GITHUB_BRANCH="${CODEBUILD_WEBHOOK_HEAD_REF#refs/heads/}"
      - export GITHUB_COMMIT=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export GITHUB_TAG="$(git describe --tags 2>/dev/null)"
      - echo "GITHUB_BRANCH=${GITHUB_BRANCH} GITHUB_COMMIT=${GITHUB_COMMIT} GITHUB_TAG=${GITHUB_TAG} DOCKER_IMG_TAG=${DOCKER_IMG_TAG}"
      - echo "Creating a clean environment"
      - make ci
      - echo "Check code formatting"
      - make ci-check-format
      - echo "Linting code"
      - make lint
  build:
    commands:
      - echo Build started on $(date)
      - export DOCKER_IMG_TAG=${REGISTRY}/${IMAGE_BASE_NAME}:${GITHUB_TAG}
      - export DOCKER_IMG_TAG_LATEST=${REGISTRY}/${IMAGE_BASE_NAME}:${GITHUB_BRANCH//\//_}.latest
      - |-
        if [ "${GITHUB_TAG}" = "" ] ; then
          export DOCKER_IMG_TAG=${REGISTRY}/${IMAGE_BASE_NAME}:${GITHUB_BRANCH//\//_}.${GITHUB_COMMIT}
          export GITHUB_TAG=${GITHUB_COMMIT}
        fi
      - echo "Building docker image with tags ${DOCKER_IMG_TAG} and ${DOCKER_IMG_TAG_LATEST}"
      - >
        docker build
        --build-arg GIT_HASH="${GITHUB_COMMIT}"
        --build-arg GIT_BRANCH="${GITHUB_BRANCH}"
        --build-arg VERSION="${GITHUB_TAG}"
        --build-arg AUTHOR="CI"
        -t ${DOCKER_IMG_TAG} -t ${DOCKER_IMG_TAG_LATEST} .

  post_build:
    commands:
      - echo "Unit testing..."
      - make test
      # Only push image to dockerhub for merge to develop and master
      - |
        if [ "${GITHUB_BRANCH}" = "master" ]; then
          echo "Pushing ${DOCKER_IMG_TAG} to dockerhub"
          docker push ${DOCKER_IMG_TAG}
        fi
      - |
        if [ "${GITHUB_BRANCH}" = "develop" ]; then
          echo "Pushing ${DOCKER_IMG_TAG} and ${DOCKER_IMG_TAG_LATEST} to dockerhub"
          docker push ${DOCKER_IMG_TAG}
          docker push ${DOCKER_IMG_TAG_LATEST}
        fi
