version: 0.2

env:
  variables:
    IMAGE_BASE_NAME: "swisstopo/service-name"
    SHELL: /bin/bash
    AWS_DEFAULT_REGION: eu-central-1
    USER: "aws_code_build"
    TEST_REPORT_DIR: "./tests/report"
    TEST_REPORT_FILE: "nose2-junit.xml"
    PIPENV_NOSPIN: 1
  parameter-store:
    CI_DOCKERHUB_USER: "/dockerhub/user"
    CI_DOCKERHUB_PASSWORD: "/dockerhub/password"

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo "Installing necessary softwares"
      - docker login -u ${CI_DOCKERHUB_USER} -p ${CI_DOCKERHUB_PASSWORD}
      - apt-get update && apt-get install -y docker-compose python3-pip
  pre_build:
    commands:
      - echo "export of the image tag for build and push purposes"
      # Reading git branch (the utility in the deploy script is unable to read it automatically on CodeBuild)
      # see https://stackoverflow.com/questions/47657423/get-github-git-branch-for-aws-codebuild
      - export GITHUB_BRANCH="$(git symbolic-ref HEAD --short 2>/dev/null)"
      - |
        if [ "${GITHUB_BRANCH}" = "" ] ; then
          GITHUB_BRANCH="$(git branch -a --contains HEAD | sed -n 2p | awk '{ printf $1 }')";
          export GITHUB_BRANCH=${GITHUB_BRANCH#remotes/origin/};
        fi
      - export GITHUB_COMMIT=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export GITHUB_TAG="$(git describe --tags 2>/dev/null)"
      - echo "GITHUB_BRANCH=${GITHUB_BRANCH} GITHUB_COMMIT=${GITHUB_COMMIT} GITHUB_TAG=${GITHUB_TAG} DOCKER_IMG_TAG=${DOCKER_IMG_TAG}"
      - echo "creating a clean environment"
      - make ci
  build:
    commands:
      - echo Build started on $(date)
      - export DOCKER_IMG_TAG=${IMAGE_BASE_NAME}:${GITHUB_TAG}
      - export DOCKER_IMG_TAG_LATEST=${IMAGE_BASE_NAME}:${GITHUB_BRANCH}.latest
      - |-
        if [ "${GITHUB_TAG}" = "" ] ; then
          export DOCKER_IMG_TAG=${IMAGE_BASE_NAME}:${GITHUB_BRANCH}.${GITHUB_COMMIT}
          export GITHUB_TAG=${GITHUB_COMMIT}
        fi
      - echo "Building docker image with tags ${DOCKER_IMG_TAG} and ${DOCKER_IMG_TAG_LATEST}"
      - >
        docker build
        --build-arg GIT_HASH="${GITHUB_COMMIT}"
        --build-arg GIT_BRANCH="${GITHUB_BRANCH}"
        --build-arg VERSION="${GITHUB_TAG}"
        --build-arg AUTHOR="CI"
        -t ${DOCKER_IMG_TAG} -t ${DOCKER_IMG_TAG_LATEST} .

  post_build:
    commands:
      - echo "Linting code..."
      - make lint
      - echo "Unit testing..."
      - mkdir -p ${TEST_REPORT_DIR}
      - TEST_REPORT_DIR=${TEST_REPORT_DIR} TEST_REPORT_FILE=${TEST_REPORT_FILE} make test
      # Only push image to dockerhub for merge to develop and master
      - |
         if [ "${GITHUB_BRANCH}" = "master" ]; then
          echo "Pushing ${DOCKER_IMG_TAG} to dockerhub"
          docker push ${DOCKER_IMG_TAG}
        fi
      - |
        if [ "${GITHUB_BRANCH}" = "develop" ]; then
          echo "Pushing ${DOCKER_IMG_TAG} and ${DOCKER_IMG_TAG_LATEST} to dockerhub"
          docker push ${DOCKER_IMG_TAG}
          docker push ${DOCKER_IMG_TAG_LATEST}
        fi

reports:
  nose2_reports:
    files:
      - ${TEST_REPORT_FILE}
    base-directory: ${TEST_REPORT_DIR}
    file-format: JunitXml